[package]
name = "solana-mail-program"
version = "0.1.0"
edition = "2018"
license = "MIT"
publish = false

[dependencies]
solana-program = "=1.7.11"
borsh= "0.9.1"
borsh-derive = "0.9.1"
thiserror = "1.0.30"

[features]
test-bpf = []

[lib]
crate-type = ["cdylib", "lib"]
